Fix an error when compiling with both -O0 and -Wp,-D_FORTIFY_SOURCE=2
Fix the following error happening with the gcc shipped on some Ubuntu
versions:

In file included from /usr/include/stdio.h:27:0,
                 from /home/pedro/lib/libam7xxx/src/am7xxx.c:19:
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE
requires compiling with optimization (-O) [-Werror=cpp]
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/am7xxx.dir/am7xxx.c.o] Error 1
make[1]: *** [src/CMakeFiles/am7xxx.dir/all] Error 2
make: *** [all] Error 2

Reported-by: Petr Certik <petr@certik.cz>